name:                crypto-bot-hs
version:             0.1.0
github:              "epicallan/crypto-bot-hs"
license:             BSD3
author:              "Lukwago Allan"
maintainer:          "epicallan.al@gmail.com"
copyright:           "2018 Lukwago Allan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/epicallan/crypto-bot-hs#readme>

default-extensions: OverloadedStrings NoImplicitPrelude

dependencies:
- base >= 4.7 && < 5
- protolude >= 0.2

library:
  source-dirs: src

executables:
  crypto-bot-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-bot-hs

tests:
  crypto-bot-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-bot-hs
    - hspec
    - QuickCheck
